
POST http://localhost:5000/auth/registration
Content-Type: application/json

{
    "username": "Стивен",
    "secondname": "Джеррард",
    "phonenumber": "+380123146547565",
    "login": "alex4",
    "password": "яДолбаеб"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "login": "alex10",
    "password": "яДолбаеб"
}
