DROP TABLE user_info CASCADE;
DROP TABLE image_storage CASCADE;

DROP TABLE dialog CASCADE;
DROP TABLE message_storage CASCADE;

DROP TABLE user_profile CASCADE;
DROP TABLE list_of_contacts CASCADE;

DROP TABLE IF EXISTS tmp CASCADE;